# Generated by Django 6.0 on 2025-12-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('auth', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('other', 'Other')], default='none', max_length=30)),
                ('meta_description', models.CharField(max_length=160)),
                ('api_url', models.URLField()),
                ('document_url', models.URLField()),
                ('https_support', models.BooleanField(default=False)),
                ('cors', models.BooleanField(default=False)),
                ('auth_header', models.BooleanField(default=False)),
                ('auth_query_param', models.BooleanField(default=False)),
                ('auth_basic_auth', models.BooleanField(default=False)),
                ('auth_cookie', models.BooleanField(default=False)),
                ('auth_digest', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='api.category')),
                ('tags', models.ManyToManyField(related_name='apis', to='api.tag')),
            ],
        ),
    ]
