# Generated by Django 6.0 on 2025-12-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicapi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
